export default {
  login: "vikky-10",
  id: 58542941,
  node_id: "MDQ6VXNlcjU4NTQyOTQx",
  avatar_url: "https://avatars.githubusercontent.com/u/58542941?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/vikky-10",
  html_url: "https://github.com/vikky-10",
  followers_url: "https://api.github.com/users/vikky-10/followers",
  following_url: "https://api.github.com/users/vikky-10/following{/other_user}",
  gists_url: "https://api.github.com/users/vikky-10/gists{/gist_id}",
  starred_url: "https://api.github.com/users/vikky-10/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/vikky-10/subscriptions",
  organizations_url: "https://api.github.com/users/vikky-10/orgs",
  repos_url: "https://api.github.com/users/vikky-10/repos",
  events_url: "https://api.github.com/users/vikky-10/events{/privacy}",
  received_events_url: "https://api.github.com/users/vikky-10/received_events",
  type: "User",
  site_admin: false,
  name: "vikky singh",
  company: null,
  blog: "https://elastic-borg-73e037.netlify.app/",
  location: "jalandhar",
  email: null,
  hireable: null,
  bio: "junior front-end web developer and specializing in mostly JS, React but also some other stuff.\r\n#web enthusiasts",
  twitter_username: "vikkysingh_",
  public_repos: 43,
  public_gists: 0,
  followers: 2,
  following: 11,
  created_at: "2019-12-05T05:09:05Z",
  updated_at: "2021-05-21T07:07:06Z",
};
